name: Test Action
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get diff
        run: |
          echo "diff={$(git diff origin/main HEAD}" > $GITHUB_ENV
      - name: Process diff
        uses: polupanovaanna/github_actions_test_project@latest
        with:
          masterheadhash: ${{ github.event.pull_request.base.sha }}
          diff: ${{ env.diff }}