name: Test Action
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get diff
        run: |
          echo ${GITHUB_HEAD_REF}
          echo "diff={$(git diff main ${GITHUB_HEAD_REF})}" > $GITHUB_ENV
      - name: Process diff
        uses: polupanovaanna/parse_repo_docker_action@master
        with:
          headHash: ${{ github.event.pull_request.base.sha }}
          diff: ${{ env.diff }}