name: Check pull request action
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get diff
        run: |
          echo "diff<<EOF" >> $GITHUB_ENV
          git diff origin/main HEAD >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Get affected targets
        run: |
          bazel build //:bazel-diff
          echo "targets<<EOF" >> $GITHUB_ENV
          hashMaster=$(git rev-parse origin/main HEAD | awk 'NR==1')
          hashBranch=$(git rev-parse origin/main HEAD | awk 'NR==2')
          git checkout $hashMaster --quiet
          bazel-bin/bazel-diff generate-hashes -w ${{ github.workspace }} master_hash.txt
          git checkout $hashBranch --quiet
          bazel-bin/bazel-diff generate-hashes -w ${{ github.workspace }} branch_hash.txt
          bazel-bin/bazel-diff get-impacted-targets -sh master_hash.txt -fh branch_hash.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Process info
        uses: polupanovaanna/parse_repo_docker_action@master
        with:
          headHash: ${{ github.event.pull_request.base.sha }}
          diff: ${{ env.diff }}
          host: ${{ secrets.SERVER_URL }}
          command: "bazel build //a_app:a_build"
          targets: ${{ env.targets }}