name: Check pull request action
on: [pull_request]
description: "Sending check request when crating pull request to run tests"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get diff
        run: |
          echo "diff<<EOF" >> $GITHUB_ENV
          git diff origin/main HEAD >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "targets<<EOF" >> $GITHUB_ENV
          echo "a.go" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Process diff
        uses: polupanovaanna/parse_repo_docker_action@master
        with:
          headHash: ${{ github.event.pull_request.base.sha }}
          diff: ${{ env.diff }}
          host: ${{ secrets.SERVER_URL }}
          command: "bazel build //a_app:a_build"
          targets: ${{ env.targets }}